import {
  EnvironmentData,
  McbDevice,
  AlertEvent,
  SecurityStatus,
  SystemHealthItem,
  ElectricalReading,
  FacilitySettings,
} from "../types";

/*
 * IMPORTANT
 * ----------
 * This file now contains ONLY initial UI state / fallback configuration.
 *
 * It is NOT the source of live telemetry.
 *
 * Live data will eventually come from:
 *
 * ESP32 → MQTT → FastAPI → React
 *
 * The threshold configuration below is intentionally kept here for now.
 * The actual threshold evaluation will be handled by the backend.
 */

// -----------------------------------------------------------------------------
// ENVIRONMENT
// -----------------------------------------------------------------------------
// No real sensor data has been received yet.
// Zero values prevent the UI from pretending that these are live readings.

export const environment: EnvironmentData = {
  temperature: 0,
  temperatureUnit: "°C",
  temperatureStatus: "NORMAL",

  gas: 0,
  gasUnit: "%",
  gasStatus: "NORMAL",

  humidity: 0,
  humidityUnit: "% RH",
  humidityStatus: "NORMAL",

  fireStatus: "SAFE",
  fireOpticalReading: 0,

  lastUpdated: "--:--:--",
};

// -----------------------------------------------------------------------------
// SECURITY
// -----------------------------------------------------------------------------
// Camera/CV starts in standby.
// Real detections will eventually come from the CV pipeline.

export const security: SecurityStatus = {
  cameraStatus: "STANDBY",
  fps: 0,
  activeCameraId: "CAM-01",

  personDetected: 0,
  firearmDetected: 0,

  firearmConfidence: 0,
  personConfidence: 0,

  theftProtectionArmed: false,
  intruderDetected: false,

  intruderLocation: undefined,

  cvEngineStatus: "STANDBY",
};

// -----------------------------------------------------------------------------
// MCB DEVICES
// -----------------------------------------------------------------------------
// Temporary device topology.
// Electrical telemetry values are zero until the hardware/backend provides them.

export const devices: McbDevice[] = [
  {
    id: "MCB-01",
    name: "MAIN FEEDER A",
    circuit: "400V 3-PHASE INCOMING",
    status: "OFFLINE",
    switchState: false,
    currentLoad: 0,
    maxCapacity: 32.0,
    temperature: 0,
    connectedTo: "MAIN GRID BUS",
    lastToggled: undefined,
  },
  {
    id: "MCB-02",
    name: "HVAC & COOLING TOWER",
    circuit: "230V CHILLER UNIT",
    status: "OFFLINE",
    switchState: false,
    currentLoad: 0,
    maxCapacity: 20.0,
    temperature: 0,
    connectedTo: "FEEDER-01",
    lastToggled: undefined,
  },
  {
    id: "MCB-03",
    name: "LIGHTING & AUX VAULT",
    circuit: "230V AUXILIARY",
    status: "OFFLINE",
    switchState: false,
    currentLoad: 0,
    maxCapacity: 16.0,
    temperature: 0,
    connectedTo: "FEEDER-01",
    lastToggled: undefined,
  },
  {
    id: "MCB-04",
    name: "HEAVY MACHINERY BAY",
    circuit: "400V SERVO DRIVES",
    status: "OFFLINE",
    switchState: false,
    currentLoad: 0,
    maxCapacity: 25.0,
    temperature: 0,
    connectedTo: "MAIN GRID BUS",
    lastToggled: undefined,
  },
  {
    id: "MCB-05",
    name: "SERVER RACK & UPS",
    circuit: "230V CRITICAL POWER",
    status: "OFFLINE",
    switchState: false,
    currentLoad: 0,
    maxCapacity: 16.0,
    temperature: 0,
    connectedTo: "UPS LINE 1",
    lastToggled: undefined,
  },
  {
    id: "MCB-06",
    name: "AUTOMATED EXTINGUISHER",
    circuit: "24V DC ACTUATOR BUS",
    status: "OFFLINE",
    switchState: false,
    currentLoad: 0,
    maxCapacity: 10.0,
    temperature: 0,
    connectedTo: "SAFETY BACKUP",
    lastToggled: undefined,
  },
];

// -----------------------------------------------------------------------------
// ALERTS
// -----------------------------------------------------------------------------
// Start with an empty event stream.
// Real events will be generated by the backend.

export const alerts: AlertEvent[] = [];

// -----------------------------------------------------------------------------
// SYSTEM HEALTH
// -----------------------------------------------------------------------------
// These are connection states rather than fabricated sensor readings.

export const systemHealth: SystemHealthItem[] = [
  {
    id: "sh-1",
    name: "BACKEND",
    status: "NOT CONNECTED",
    indicatorColor: "amber",
    note: "FastAPI bridge awaiting connection",
  },
  {
    id: "sh-2",
    name: "SENSORS",
    status: "WAITING FOR IOT",
    indicatorColor: "amber",
    note: "MQTT / ESP32 telemetry standby",
  },
  {
    id: "sh-3",
    name: "CAMERA",
    status: "NOT CONNECTED",
    indicatorColor: "amber",
    note: "Awaiting live camera stream",
  },
  {
    id: "sh-4",
    name: "CV ENGINE",
    status: "STANDBY",
    indicatorColor: "amber",
    note: "YOLO/OpenCV inference standby",
  },
  {
    id: "sh-5",
    name: "DATABASE",
    status: "NOT CONNECTED",
    indicatorColor: "zinc",
    note: "Persistent telemetry storage not configured",
  },
];

// -----------------------------------------------------------------------------
// ELECTRICAL METRICS
// -----------------------------------------------------------------------------
// Placeholder values until electrical hardware is connected.

export const electricalMetrics: ElectricalReading = {
  voltage: 0,
  current: 0,
  power: 0,
  energy: 0,
  frequency: 0,
  powerFactor: 0,
};

// -----------------------------------------------------------------------------
// FACILITY SETTINGS
// -----------------------------------------------------------------------------
// KEEP THESE.
// These are configuration values, not simulated telemetry.
//
// Backend threshold engine will eventually use these values.

export const defaultSettings: FacilitySettings = {
  // Temperature thresholds
  tempWarningThreshold: 45.0,
  tempCriticalThreshold: 60.0,

  // Gas thresholds
  gasWarningThreshold: 40.0,
  gasCriticalThreshold: 70.0,

  // CV threshold
  cvConfidenceThreshold: 80,

  // Emergency controls
  extinguisherPin: "1234",
  audioAlarmEnabled: true,

  // Automatic safety actions
  autoTripOnCriticalGas: true,
  autoTripOnFire: true,

  // Frontend polling configuration
  pollingRateMs: 2000,

  // Camera settings
  nightVisionMode: false,
  reticleOverlay: true,
};

// -----------------------------------------------------------------------------
// SENSOR HISTORY
// -----------------------------------------------------------------------------
// No fabricated history.
// This will eventually be populated from backend/database telemetry.

export const historicalSensorData: {
  time: string;
  temp: number;
  gas: number;
  humidity: number;
}[] = [];
